### ISSUE TITLE
PR Harmony Settings Page Blank

### ISSUE THREAD

**Issue by KyleMit** [monitorjbl/pr-harmony#20] opened 2015-09-24 19:23 UTC
PR Harmony is installed and the option is available from the project and repository settings pages.

However, when I click on the link, I am just redirected to a blank page:

**Project**: http://_servername_:7990/plugins/servlet/pr-harmony/_project-name_
**Repo**: http://_servername_:7990/plugins/servlet/pr-harmony/_project-name_/_repo-name_

Looking at View Source for the page reveals nothing even attempting to be delivered.

Here's an example on the box itself against localhost which returns a 403.  Normally it finds the url and just returns a white page.

![Example](http://i.imgur.com/FKAYgPk.gif)

**Stash Build Version**: 3.9.2
**PR Harmony Version**: 1.6

**Comment by monitorjbl** [comment] 2015-09-26 18:05
Hm, this is interesting...I don't think it's the plugin itself so much as your auth details not being preserved when changing contexts. Does this happen in other browsers? I don't have Windows, so I can't test IE myself.

**Comment by monitorjbl** [comment] 2015-10-06 01:20
@KyleMit Any update?

**Comment by KyleMit** [comment] 2015-10-06 15:44
Happening on Windows 7 in all of the following browsers:

**Chrome**: 45.0.2
**Firefox**: 41.0.1
**Internet Explorer**: 11.0

I can attach screenshots of each, but they're all the same - the rest of the project settings work fine, but the PR Harmony add on settings returns a blank page.

**Comment by monitorjbl** [comment] 2015-10-23 18:26
@KyleMit I released version 4.0 for Bitbucket today, if you're using that version can you give it another shot and see if it's still happening?

**Comment by ppuschmann** [comment] 2015-11-16 14:47
Same problem here (white page / empty page) with:

**Stash Build Version**: 3.10.0
**PR Harmony Version**: 2.0

@KyleMit It is no a problem of your client, but a server-side problem

**Comment by monitorjbl** [comment] 2015-11-16 15:04
@ppuschmann Version 2.0 of the plugin does not support Stash 3.x, it only supports Bitbucket 4.0. Atlassian renamed basically every Stash-related API when they rebranded to Bitbucket. I'm not even sure how your server started up the 2.0 plugin at all, it references a ton of classes that don't exist in pre-4.0 servers.

**Comment by ppuschmann** [comment] 2015-11-17 13:47
@monitorjbl with using v1.8 we had the same issue...
(and I was mistaken, we have v1.8 installed, v2.0 is available..., sorry)

Any hints which log-files might give a glance of information?

**Comment by gawlik** [comment] 2015-12-14 10:52
We have the same behaviour, it works for some users but for others don't.
I cannot see anything else in logs except of 403 response code:

IP | http | -- | <USER> | 2015-12-14 05:32:44,944 | "GET /plugins/servlet/pr-harmony/<PROJECT> HTTP/1.1" | "http://<host>:7990/projects/PROJECT_NAME/settings" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36" | 403 | 0 | 0 | - | 4 | 7w601b |

We use:
- Atlassian Bitbucket v4.0.1 (Data Center)
- PR Harmony 2.1

Can we build that add-on with some debugging mode? We have debug logging and profiling already turned on.

**Comment by mkrakowitzer** [comment] 2016-01-27 04:47
Experiencing this same issue, stash 3.6.1 with version 1.6 of the plugin.

**Comment by monitorjbl** [comment] 2016-02-05 19:44
If you're using Bitbucket 4.0+, can you give the latest version of the plugin a try? An issue with symptoms similar to this was reported in #31 and turned out to be the uppercase characters in the LDAP user names.

**Comment by gawlik** [comment] 2016-04-11 15:11
Yeap, looks like https://github.com/monitorjbl/pr-harmony/issues/31 resolved that problem. Thank you!

**Comment by monitorjbl** [comment] 2016-04-18 01:17
Thanks for the feedback! Closing this issue out as I believe the root cause of the problem has been eliminated.

**Closed as completed by monitorjbl** 2016-04-18 01:17 UTC
Labels: bug, info needed
